### ISSUE TITLE
Get column name from the Json itself?

### ISSUE THREAD

**Issue by ron819** [jsnell/json-to-multicsv#1]
In the current script the table names must be given as input.
How can it be converted so the table names will be generated from the JSON itself?

In the example: https://www.snellman.net/blog/archive/2016-01-12-json-to-multicsv/

The table names are the list names so the code doesn't need to get it as parameters.
Only the node name needs to be given as paramter...

So the call should be:

SCRIPT   NodeName  json_source  output_folder

The csv file names are created from the json itself : NodeName, NodeName_genres, NodeName_sales

Also, what happens if there is Json inside the array?

**Comment by jsnell** [comment]
You appear to be asking for no command line options at all. That is not possible; as explained in the blog post, there are many possible ways the structure of the JSON file could be interpreted. For example in the example file there are objects that create a new table (i.e. every key in the object is a new row). The root object is an example of that. And then there are objects where the keys are instead new columns in the current row. The "rating" object is an example of that. 

The decision of which interpretation is correct can't be made by the program, it requires a human who understand the data to make the call.

If I misunderstood, and you're not asking for the command line arguments to go away completely but just want the table argument to look like:

    --path /*/sales:table

... rather than:

    --path /*/sales:table:sales

... that would be possible. But I don't think that buys very much. You'd still need the rest of the arguments, and it'd make it hard to deal with cases where the automatically generated table name is not a valid filename.

> Also, what happens if there is Json inside the array?

That depends on how you tell the converter to treat the data. If you ask for the list to be interpreted as a new table (like "sales" is in the example), the JSON objects inside the array would be be considered rows in a new table. Or you can ask for the list to be converted to columns, which would apply transitively into the nested JSON objects. Or you could drop the list completely with :ignore

**Comment by kupietools** [comment]
I disagree.It's true you may need the user to provide a top-level table name (if you don't want to include a default top-level table name in the script) but child table names are easy to determine: 

`{"A": {"B":1}}` means there is a child table named "A", and there is a field named "B" in that table, and a single record in it.
`{"A": [{"B":1},{"B":2}]}` means there is a child table named "A", and there is a field named "B" in that table, and a two records in it.

Any key whose value is an object or array is a child table. 

The sole odd case is if you have something like `{"A":{"B":[[1,3],[3,4]}}`, in which case no name is explicitly defined for the child table. In that case, it creates child table "B" and then defaults to naming the table containing the sub-array values "B_childtable". It will keep appending "_childtable" as deep as you want to nest arrays. The field name in "B_childtable" will default to "B_childtable_field1" since there's no key to provide a name. 

I know this scheme works perfectly fine because I already have this working in another language, and it fully works and can handle anything I throw at it, but it's just too slow so I'm looking for a PERL solution. (I'm a FileMaker Pro developer, it's a FileMaker script.) The only problem is I'm not good enough at PERL to convert my working code it it. 

But as far as algorithms being unable to decide what should be a table and what shouldn't, I can tell you for 100% sure that as long as you define a default top-level table name in the code it's not an absolute requirement for users to provide any input, and if you don't provide the default then the only required user input is the top-level table name, because I have working code that behaves that way, accepts arbitrary JSON and it farms everything out to CSVs by the logic above, giving them correct table and field names without issue.

**Comment by jsnell** [comment]
> {"A": {"B":1}} means there is a child table named "A", and there is a field named "B" in that table, and a single record in it.

It could mean that. It could also mean that you want a table with the column "a.b", or a single table with a column "b" and with a row "a".
